// Generato automaticamente: non modificare a mano, modifica gen_i18n.py
window.EOL_LANGS = ["it", "en", "es", "fr", "de", "pt", "ru", "zh", "ja", "ar"];
window.EOL_LANG_NAMES = {"it": "Italiano", "en": "English", "es": "Español", "fr": "Français", "de": "Deutsch", "pt": "Português", "ru": "Русский", "zh": "中文", "ja": "日本語", "ar": "العربية"};
window.EOL_RTL = ["ar"];
window.EOL_STRINGS = {
 "it": {
  "url_placeholder": "Scrivi un indirizzo o cerca…",
  "go": "Vai",
  "search_placeholder": "Cerca",
  "back": "Indietro",
  "forward": "Avanti",
  "stop": "Stop",
  "reload": "Aggiorna",
  "home": "Home",
  "favorites": "Preferiti",
  "history": "Cronologia",
  "channels": "Canali",
  "find_label": "Trova:",
  "err_title": "Impossibile aprire la pagina",
  "err_retry": "Riprova",
  "status_done": "Fatto",
  "status_local": "🏠 Locale",
  "status_secure": "🔒 Connessione sicura",
  "status_internet": "🌐 Internet",
  "status_opening": "Apertura di %s…",
  "status_fav_added": "Aggiunto ai preferiti: %s",
  "status_fav_home": "La pagina iniziale non si può aggiungere ai preferiti",
  "status_addr_copied": "Indirizzo copiato",
  "status_engine": "Motore predefinito: %s",
  "status_hist_cleared": "Cronologia cancellata",
  "status_tm_on": "Macchina del tempo attiva: i siti si aprono come nel 1999",
  "status_tm_off": "Macchina del tempo disattivata",
  "tab_home": "Pagina iniziale",
  "panel_fav_empty": "Nessun preferito. Apri una pagina e premi Ctrl+D.",
  "panel_hist_empty": "La cronologia è vuota.",
  "menu_file": "File",
  "menu_file_newtab": "Nuova scheda",
  "menu_file_closetab": "Chiudi scheda",
  "menu_edit": "Modifica",
  "menu_edit_copyaddr": "Copia indirizzo",
  "menu_edit_selectaddr": "Seleziona indirizzo",
  "menu_edit_find": "Trova nella pagina",
  "menu_view": "Visualizza",
  "menu_view_reload": "Aggiorna",
  "menu_view_home": "Pagina iniziale",
  "menu_view_zoomin": "Ingrandisci",
  "menu_view_zoomout": "Riduci",
  "menu_view_zoomreset": "Zoom normale",
  "menu_view_fullscreen": "Schermo intero",
  "menu_fav": "Preferiti",
  "menu_fav_add": "Aggiungi ai preferiti",
  "menu_fav_show": "Mostra preferiti",
  "menu_fav_showhist": "Mostra cronologia",
  "menu_tools": "Strumenti",
  "menu_tools_tm": "Macchina del tempo (web del 1999)",
  "menu_tools_theme_eol": "Tema EOL",
  "menu_tools_theme_classic": "Tema Classic 98",
  "menu_tools_theme_aqua": "Tema Aqua 2000",
  "menu_tools_theme_night": "Tema Notte neon",
  "menu_tools_engine": "Cerca con %s",
  "menu_tools_devtools": "Strumenti per sviluppatori",
  "menu_tools_clearhist": "Cancella cronologia",
  "menu_tools_lang": "Lingua",
  "menu_help": "?",
  "menu_help_about": "Informazioni su EOL Explorer",
  "about_body": "EOL Explorer 1.0<br><br>Il browser con l'aspetto degli anni '90 e il motore di oggi (Chromium).",
  "home_search_placeholder": "Cosa cerchi oggi?",
  "home_search_btn": "Cerca",
  "home_cat_web": "Web",
  "home_cat_images": "Immagini",
  "home_cat_video": "Video",
  "home_cat_news": "Notizie",
  "home_cat_maps": "Mappe",
  "home_tab_explore": "Esplora",
  "home_tab_retro": "Retro",
  "home_tab_fun": "Svago",
  "home_tab_tools": "Strumenti",
  "home_hero_title": "Torna al 1999",
  "home_hero_text": "Con la Macchina del tempo ogni sito si apre com'era nel 1999, grazie all'Internet Archive.",
  "home_tm_on": "⏪ Macchina del tempo: ATTIVA (disattiva)",
  "home_tm_off": "⏪ Attiva la Macchina del tempo",
  "home_lcd_time": "Ora esatta",
  "home_lcd_visits": "Visitatori",
  "home_favs_title": "I tuoi preferiti",
  "home_favs_empty": "Ancora nessuno.",
  "greet_morning": "Buongiorno",
  "greet_afternoon": "Buon pomeriggio",
  "greet_evening": "Buonasera",
  "home_marquee": "★ Benvenuto su EOL Explorer ★ Il browser che naviga come nel 1999, ma va veloce come oggi ★ Risoluzione consigliata 800x600 (ma va bene anche 4K) ★ Sito in costruzione 🚧 ★"
 },
 "en": {
  "url_placeholder": "Type an address or search…",
  "go": "Go",
  "search_placeholder": "Search",
  "back": "Back",
  "forward": "Forward",
  "stop": "Stop",
  "reload": "Reload",
  "home": "Home",
  "favorites": "Favorites",
  "history": "History",
  "channels": "Channels",
  "find_label": "Find:",
  "err_title": "Couldn't open the page",
  "err_retry": "Retry",
  "status_done": "Done",
  "status_local": "🏠 Local",
  "status_secure": "🔒 Secure connection",
  "status_internet": "🌐 Internet",
  "status_opening": "Opening %s…",
  "status_fav_added": "Added to favorites: %s",
  "status_fav_home": "The home page can't be added to favorites",
  "status_addr_copied": "Address copied",
  "status_engine": "Default engine: %s",
  "status_hist_cleared": "History cleared",
  "status_tm_on": "Time Machine on: sites open as they looked in 1999",
  "status_tm_off": "Time Machine off",
  "tab_home": "Home page",
  "panel_fav_empty": "No favorites yet. Open a page and press Ctrl+D.",
  "panel_hist_empty": "History is empty.",
  "menu_file": "File",
  "menu_file_newtab": "New tab",
  "menu_file_closetab": "Close tab",
  "menu_edit": "Edit",
  "menu_edit_copyaddr": "Copy address",
  "menu_edit_selectaddr": "Select address",
  "menu_edit_find": "Find in page",
  "menu_view": "View",
  "menu_view_reload": "Reload",
  "menu_view_home": "Home page",
  "menu_view_zoomin": "Zoom in",
  "menu_view_zoomout": "Zoom out",
  "menu_view_zoomreset": "Reset zoom",
  "menu_view_fullscreen": "Full screen",
  "menu_fav": "Favorites",
  "menu_fav_add": "Add to favorites",
  "menu_fav_show": "Show favorites",
  "menu_fav_showhist": "Show history",
  "menu_tools": "Tools",
  "menu_tools_tm": "Time Machine (1999 web)",
  "menu_tools_theme_eol": "EOL theme",
  "menu_tools_theme_classic": "Classic 98 theme",
  "menu_tools_theme_aqua": "Aqua 2000 theme",
  "menu_tools_theme_night": "Neon Night theme",
  "menu_tools_engine": "Search with %s",
  "menu_tools_devtools": "Developer tools",
  "menu_tools_clearhist": "Clear history",
  "menu_tools_lang": "Language",
  "menu_help": "?",
  "menu_help_about": "About EOL Explorer",
  "about_body": "EOL Explorer 1.0<br><br>The browser with a 90s look and today's engine (Chromium).",
  "home_search_placeholder": "What are you looking for today?",
  "home_search_btn": "Search",
  "home_cat_web": "Web",
  "home_cat_images": "Images",
  "home_cat_video": "Video",
  "home_cat_news": "News",
  "home_cat_maps": "Maps",
  "home_tab_explore": "Explore",
  "home_tab_retro": "Retro",
  "home_tab_fun": "Fun",
  "home_tab_tools": "Tools",
  "home_hero_title": "Back to 1999",
  "home_hero_text": "With the Time Machine, every site opens as it looked in 1999, thanks to the Internet Archive.",
  "home_tm_on": "⏪ Time Machine: ON (turn off)",
  "home_tm_off": "⏪ Turn on the Time Machine",
  "home_lcd_time": "Current time",
  "home_lcd_visits": "Visitors",
  "home_favs_title": "Your favorites",
  "home_favs_empty": "None yet.",
  "greet_morning": "Good morning",
  "greet_afternoon": "Good afternoon",
  "greet_evening": "Good evening",
  "home_marquee": "★ Welcome to EOL Explorer ★ The browser that browses like 1999, but runs as fast as today ★ Recommended resolution 800x600 (but 4K works fine too) ★ Site under construction 🚧 ★"
 },
 "es": {
  "url_placeholder": "Escribe una dirección o busca…",
  "go": "Ir",
  "search_placeholder": "Buscar",
  "back": "Atrás",
  "forward": "Adelante",
  "stop": "Detener",
  "reload": "Recargar",
  "home": "Inicio",
  "favorites": "Favoritos",
  "history": "Historial",
  "channels": "Canales",
  "find_label": "Buscar:",
  "err_title": "No se pudo abrir la página",
  "err_retry": "Reintentar",
  "status_done": "Listo",
  "status_local": "🏠 Local",
  "status_secure": "🔒 Conexión segura",
  "status_internet": "🌐 Internet",
  "status_opening": "Abriendo %s…",
  "status_fav_added": "Añadido a favoritos: %s",
  "status_fav_home": "La página de inicio no se puede añadir a favoritos",
  "status_addr_copied": "Dirección copiada",
  "status_engine": "Motor predeterminado: %s",
  "status_hist_cleared": "Historial borrado",
  "status_tm_on": "Máquina del tiempo activada: los sitios se abren como en 1999",
  "status_tm_off": "Máquina del tiempo desactivada",
  "tab_home": "Página de inicio",
  "panel_fav_empty": "Aún no hay favoritos. Abre una página y pulsa Ctrl+D.",
  "panel_hist_empty": "El historial está vacío.",
  "menu_file": "Archivo",
  "menu_file_newtab": "Nueva pestaña",
  "menu_file_closetab": "Cerrar pestaña",
  "menu_edit": "Editar",
  "menu_edit_copyaddr": "Copiar dirección",
  "menu_edit_selectaddr": "Seleccionar dirección",
  "menu_edit_find": "Buscar en la página",
  "menu_view": "Ver",
  "menu_view_reload": "Recargar",
  "menu_view_home": "Página de inicio",
  "menu_view_zoomin": "Acercar",
  "menu_view_zoomout": "Alejar",
  "menu_view_zoomreset": "Restablecer zoom",
  "menu_view_fullscreen": "Pantalla completa",
  "menu_fav": "Favoritos",
  "menu_fav_add": "Añadir a favoritos",
  "menu_fav_show": "Mostrar favoritos",
  "menu_fav_showhist": "Mostrar historial",
  "menu_tools": "Herramientas",
  "menu_tools_tm": "Máquina del tiempo (web de 1999)",
  "menu_tools_theme_eol": "Tema EOL",
  "menu_tools_theme_classic": "Tema Classic 98",
  "menu_tools_theme_aqua": "Tema Aqua 2000",
  "menu_tools_theme_night": "Tema Noche neón",
  "menu_tools_engine": "Buscar con %s",
  "menu_tools_devtools": "Herramientas de desarrollo",
  "menu_tools_clearhist": "Borrar historial",
  "menu_tools_lang": "Idioma",
  "menu_help": "?",
  "menu_help_about": "Acerca de EOL Explorer",
  "about_body": "EOL Explorer 1.0<br><br>El navegador con aspecto de los 90 y el motor de hoy (Chromium).",
  "home_search_placeholder": "¿Qué buscas hoy?",
  "home_search_btn": "Buscar",
  "home_cat_web": "Web",
  "home_cat_images": "Imágenes",
  "home_cat_video": "Vídeo",
  "home_cat_news": "Noticias",
  "home_cat_maps": "Mapas",
  "home_tab_explore": "Explorar",
  "home_tab_retro": "Retro",
  "home_tab_fun": "Ocio",
  "home_tab_tools": "Herramientas",
  "home_hero_title": "Vuelve a 1999",
  "home_hero_text": "Con la Máquina del tiempo, cada sitio se abre como era en 1999, gracias a Internet Archive.",
  "home_tm_on": "⏪ Máquina del tiempo: ACTIVADA (desactivar)",
  "home_tm_off": "⏪ Activar la Máquina del tiempo",
  "home_lcd_time": "Hora actual",
  "home_lcd_visits": "Visitantes",
  "home_favs_title": "Tus favoritos",
  "home_favs_empty": "Todavía ninguno.",
  "greet_morning": "Buenos días",
  "greet_afternoon": "Buenas tardes",
  "greet_evening": "Buenas noches",
  "home_marquee": "★ Bienvenido a EOL Explorer ★ El navegador que navega como en 1999, pero va rápido como hoy ★ Resolución recomendada 800x600 (pero 4K también funciona) ★ Sitio en construcción 🚧 ★"
 },
 "fr": {
  "url_placeholder": "Saisissez une adresse ou une recherche…",
  "go": "OK",
  "search_placeholder": "Rechercher",
  "back": "Précédent",
  "forward": "Suivant",
  "stop": "Arrêter",
  "reload": "Actualiser",
  "home": "Accueil",
  "favorites": "Favoris",
  "history": "Historique",
  "channels": "Chaînes",
  "find_label": "Rechercher :",
  "err_title": "Impossible d'ouvrir la page",
  "err_retry": "Réessayer",
  "status_done": "Terminé",
  "status_local": "🏠 Local",
  "status_secure": "🔒 Connexion sécurisée",
  "status_internet": "🌐 Internet",
  "status_opening": "Ouverture de %s…",
  "status_fav_added": "Ajouté aux favoris : %s",
  "status_fav_home": "La page d'accueil ne peut pas être ajoutée aux favoris",
  "status_addr_copied": "Adresse copiée",
  "status_engine": "Moteur par défaut : %s",
  "status_hist_cleared": "Historique effacé",
  "status_tm_on": "Machine à remonter le temps activée : les sites s'ouvrent comme en 1999",
  "status_tm_off": "Machine à remonter le temps désactivée",
  "tab_home": "Page d'accueil",
  "panel_fav_empty": "Aucun favori pour l'instant. Ouvrez une page et appuyez sur Ctrl+D.",
  "panel_hist_empty": "L'historique est vide.",
  "menu_file": "Fichier",
  "menu_file_newtab": "Nouvel onglet",
  "menu_file_closetab": "Fermer l'onglet",
  "menu_edit": "Édition",
  "menu_edit_copyaddr": "Copier l'adresse",
  "menu_edit_selectaddr": "Sélectionner l'adresse",
  "menu_edit_find": "Rechercher dans la page",
  "menu_view": "Affichage",
  "menu_view_reload": "Actualiser",
  "menu_view_home": "Page d'accueil",
  "menu_view_zoomin": "Zoom avant",
  "menu_view_zoomout": "Zoom arrière",
  "menu_view_zoomreset": "Zoom normal",
  "menu_view_fullscreen": "Plein écran",
  "menu_fav": "Favoris",
  "menu_fav_add": "Ajouter aux favoris",
  "menu_fav_show": "Afficher les favoris",
  "menu_fav_showhist": "Afficher l'historique",
  "menu_tools": "Outils",
  "menu_tools_tm": "Machine à remonter le temps (web de 1999)",
  "menu_tools_theme_eol": "Thème EOL",
  "menu_tools_theme_classic": "Thème Classic 98",
  "menu_tools_theme_aqua": "Thème Aqua 2000",
  "menu_tools_theme_night": "Thème Nuit néon",
  "menu_tools_engine": "Rechercher avec %s",
  "menu_tools_devtools": "Outils de développement",
  "menu_tools_clearhist": "Effacer l'historique",
  "menu_tools_lang": "Langue",
  "menu_help": "?",
  "menu_help_about": "À propos d'EOL Explorer",
  "about_body": "EOL Explorer 1.0<br><br>Le navigateur à l'apparence des années 90 et au moteur d'aujourd'hui (Chromium).",
  "home_search_placeholder": "Que cherchez-vous aujourd'hui ?",
  "home_search_btn": "Rechercher",
  "home_cat_web": "Web",
  "home_cat_images": "Images",
  "home_cat_video": "Vidéos",
  "home_cat_news": "Actualités",
  "home_cat_maps": "Cartes",
  "home_tab_explore": "Explorer",
  "home_tab_retro": "Rétro",
  "home_tab_fun": "Loisirs",
  "home_tab_tools": "Outils",
  "home_hero_title": "Retour en 1999",
  "home_hero_text": "Avec la Machine à remonter le temps, chaque site s'ouvre comme en 1999, grâce à Internet Archive.",
  "home_tm_on": "⏪ Machine à remonter le temps : ACTIVÉE (désactiver)",
  "home_tm_off": "⏪ Activer la Machine à remonter le temps",
  "home_lcd_time": "Heure actuelle",
  "home_lcd_visits": "Visiteurs",
  "home_favs_title": "Vos favoris",
  "home_favs_empty": "Aucun pour l'instant.",
  "greet_morning": "Bonjour",
  "greet_afternoon": "Bon après-midi",
  "greet_evening": "Bonsoir",
  "home_marquee": "★ Bienvenue sur EOL Explorer ★ Le navigateur qui navigue comme en 1999, mais aussi vite qu'aujourd'hui ★ Résolution recommandée 800x600 (mais la 4K fonctionne aussi) ★ Site en construction 🚧 ★"
 },
 "de": {
  "url_placeholder": "Adresse eingeben oder suchen…",
  "go": "Los",
  "search_placeholder": "Suchen",
  "back": "Zurück",
  "forward": "Vor",
  "stop": "Stopp",
  "reload": "Neu laden",
  "home": "Startseite",
  "favorites": "Favoriten",
  "history": "Verlauf",
  "channels": "Kanäle",
  "find_label": "Suchen:",
  "err_title": "Seite konnte nicht geöffnet werden",
  "err_retry": "Erneut versuchen",
  "status_done": "Fertig",
  "status_local": "🏠 Lokal",
  "status_secure": "🔒 Sichere Verbindung",
  "status_internet": "🌐 Internet",
  "status_opening": "%s wird geöffnet…",
  "status_fav_added": "Zu Favoriten hinzugefügt: %s",
  "status_fav_home": "Die Startseite kann nicht zu Favoriten hinzugefügt werden",
  "status_addr_copied": "Adresse kopiert",
  "status_engine": "Standardsuchmaschine: %s",
  "status_hist_cleared": "Verlauf gelöscht",
  "status_tm_on": "Zeitmaschine aktiv: Seiten öffnen sich wie 1999",
  "status_tm_off": "Zeitmaschine deaktiviert",
  "tab_home": "Startseite",
  "panel_fav_empty": "Noch keine Favoriten. Öffne eine Seite und drücke Strg+D.",
  "panel_hist_empty": "Der Verlauf ist leer.",
  "menu_file": "Datei",
  "menu_file_newtab": "Neuer Tab",
  "menu_file_closetab": "Tab schließen",
  "menu_edit": "Bearbeiten",
  "menu_edit_copyaddr": "Adresse kopieren",
  "menu_edit_selectaddr": "Adresse auswählen",
  "menu_edit_find": "In Seite suchen",
  "menu_view": "Ansicht",
  "menu_view_reload": "Neu laden",
  "menu_view_home": "Startseite",
  "menu_view_zoomin": "Vergrößern",
  "menu_view_zoomout": "Verkleinern",
  "menu_view_zoomreset": "Zoom zurücksetzen",
  "menu_view_fullscreen": "Vollbild",
  "menu_fav": "Favoriten",
  "menu_fav_add": "Zu Favoriten hinzufügen",
  "menu_fav_show": "Favoriten anzeigen",
  "menu_fav_showhist": "Verlauf anzeigen",
  "menu_tools": "Extras",
  "menu_tools_tm": "Zeitmaschine (Web von 1999)",
  "menu_tools_theme_eol": "EOL-Design",
  "menu_tools_theme_classic": "Classic-98-Design",
  "menu_tools_theme_aqua": "Aqua-2000-Design",
  "menu_tools_theme_night": "Neon-Nacht-Design",
  "menu_tools_engine": "Suchen mit %s",
  "menu_tools_devtools": "Entwicklertools",
  "menu_tools_clearhist": "Verlauf löschen",
  "menu_tools_lang": "Sprache",
  "menu_help": "?",
  "menu_help_about": "Über EOL Explorer",
  "about_body": "EOL Explorer 1.0<br><br>Der Browser im 90er-Look mit der Technik von heute (Chromium).",
  "home_search_placeholder": "Wonach suchst du heute?",
  "home_search_btn": "Suchen",
  "home_cat_web": "Web",
  "home_cat_images": "Bilder",
  "home_cat_video": "Videos",
  "home_cat_news": "News",
  "home_cat_maps": "Karten",
  "home_tab_explore": "Entdecken",
  "home_tab_retro": "Retro",
  "home_tab_fun": "Freizeit",
  "home_tab_tools": "Werkzeuge",
  "home_hero_title": "Zurück ins Jahr 1999",
  "home_hero_text": "Mit der Zeitmaschine öffnet sich jede Seite so, wie sie 1999 aussah – dank des Internet Archive.",
  "home_tm_on": "⏪ Zeitmaschine: AN (ausschalten)",
  "home_tm_off": "⏪ Zeitmaschine aktivieren",
  "home_lcd_time": "Aktuelle Uhrzeit",
  "home_lcd_visits": "Besucher",
  "home_favs_title": "Deine Favoriten",
  "home_favs_empty": "Noch keine.",
  "greet_morning": "Guten Morgen",
  "greet_afternoon": "Guten Tag",
  "greet_evening": "Guten Abend",
  "home_marquee": "★ Willkommen bei EOL Explorer ★ Der Browser, der wie 1999 surft, aber so schnell wie heute läuft ★ Empfohlene Auflösung 800x600 (aber auch 4K funktioniert) ★ Seite im Aufbau 🚧 ★"
 },
 "pt": {
  "url_placeholder": "Digite um endereço ou pesquise…",
  "go": "Ir",
  "search_placeholder": "Pesquisar",
  "back": "Voltar",
  "forward": "Avançar",
  "stop": "Parar",
  "reload": "Recarregar",
  "home": "Início",
  "favorites": "Favoritos",
  "history": "Histórico",
  "channels": "Canais",
  "find_label": "Localizar:",
  "err_title": "Não foi possível abrir a página",
  "err_retry": "Tentar novamente",
  "status_done": "Concluído",
  "status_local": "🏠 Local",
  "status_secure": "🔒 Conexão segura",
  "status_internet": "🌐 Internet",
  "status_opening": "Abrindo %s…",
  "status_fav_added": "Adicionado aos favoritos: %s",
  "status_fav_home": "A página inicial não pode ser adicionada aos favoritos",
  "status_addr_copied": "Endereço copiado",
  "status_engine": "Mecanismo padrão: %s",
  "status_hist_cleared": "Histórico apagado",
  "status_tm_on": "Máquina do tempo ativa: os sites abrem como em 1999",
  "status_tm_off": "Máquina do tempo desativada",
  "tab_home": "Página inicial",
  "panel_fav_empty": "Ainda sem favoritos. Abra uma página e pressione Ctrl+D.",
  "panel_hist_empty": "O histórico está vazio.",
  "menu_file": "Arquivo",
  "menu_file_newtab": "Nova aba",
  "menu_file_closetab": "Fechar aba",
  "menu_edit": "Editar",
  "menu_edit_copyaddr": "Copiar endereço",
  "menu_edit_selectaddr": "Selecionar endereço",
  "menu_edit_find": "Localizar na página",
  "menu_view": "Exibir",
  "menu_view_reload": "Recarregar",
  "menu_view_home": "Página inicial",
  "menu_view_zoomin": "Ampliar",
  "menu_view_zoomout": "Reduzir",
  "menu_view_zoomreset": "Zoom normal",
  "menu_view_fullscreen": "Tela cheia",
  "menu_fav": "Favoritos",
  "menu_fav_add": "Adicionar aos favoritos",
  "menu_fav_show": "Mostrar favoritos",
  "menu_fav_showhist": "Mostrar histórico",
  "menu_tools": "Ferramentas",
  "menu_tools_tm": "Máquina do tempo (web de 1999)",
  "menu_tools_theme_eol": "Tema EOL",
  "menu_tools_theme_classic": "Tema Classic 98",
  "menu_tools_theme_aqua": "Tema Aqua 2000",
  "menu_tools_theme_night": "Tema Noite neon",
  "menu_tools_engine": "Pesquisar com %s",
  "menu_tools_devtools": "Ferramentas do desenvolvedor",
  "menu_tools_clearhist": "Limpar histórico",
  "menu_tools_lang": "Idioma",
  "menu_help": "?",
  "menu_help_about": "Sobre o EOL Explorer",
  "about_body": "EOL Explorer 1.0<br><br>O navegador com visual dos anos 90 e o motor de hoje (Chromium).",
  "home_search_placeholder": "O que você procura hoje?",
  "home_search_btn": "Pesquisar",
  "home_cat_web": "Web",
  "home_cat_images": "Imagens",
  "home_cat_video": "Vídeo",
  "home_cat_news": "Notícias",
  "home_cat_maps": "Mapas",
  "home_tab_explore": "Explorar",
  "home_tab_retro": "Retrô",
  "home_tab_fun": "Diversão",
  "home_tab_tools": "Ferramentas",
  "home_hero_title": "Volte a 1999",
  "home_hero_text": "Com a Máquina do tempo, cada site abre como era em 1999, graças ao Internet Archive.",
  "home_tm_on": "⏪ Máquina do tempo: ATIVA (desativar)",
  "home_tm_off": "⏪ Ativar a Máquina do tempo",
  "home_lcd_time": "Hora atual",
  "home_lcd_visits": "Visitantes",
  "home_favs_title": "Seus favoritos",
  "home_favs_empty": "Ainda nenhum.",
  "greet_morning": "Bom dia",
  "greet_afternoon": "Boa tarde",
  "greet_evening": "Boa noite",
  "home_marquee": "★ Bem-vindo ao EOL Explorer ★ O navegador que navega como em 1999, mas é rápido como hoje ★ Resolução recomendada 800x600 (mas 4K também funciona) ★ Site em construção 🚧 ★"
 },
 "ru": {
  "url_placeholder": "Введите адрес или запрос…",
  "go": "Перейти",
  "search_placeholder": "Поиск",
  "back": "Назад",
  "forward": "Вперёд",
  "stop": "Стоп",
  "reload": "Обновить",
  "home": "Домой",
  "favorites": "Избранное",
  "history": "История",
  "channels": "Каналы",
  "find_label": "Найти:",
  "err_title": "Не удалось открыть страницу",
  "err_retry": "Повторить",
  "status_done": "Готово",
  "status_local": "🏠 Локально",
  "status_secure": "🔒 Безопасное соединение",
  "status_internet": "🌐 Интернет",
  "status_opening": "Открывается %s…",
  "status_fav_added": "Добавлено в избранное: %s",
  "status_fav_home": "Домашнюю страницу нельзя добавить в избранное",
  "status_addr_copied": "Адрес скопирован",
  "status_engine": "Поисковая система по умолчанию: %s",
  "status_hist_cleared": "История очищена",
  "status_tm_on": "Машина времени включена: сайты открываются как в 1999 году",
  "status_tm_off": "Машина времени выключена",
  "tab_home": "Домашняя страница",
  "panel_fav_empty": "Пока нет избранного. Откройте страницу и нажмите Ctrl+D.",
  "panel_hist_empty": "История пуста.",
  "menu_file": "Файл",
  "menu_file_newtab": "Новая вкладка",
  "menu_file_closetab": "Закрыть вкладку",
  "menu_edit": "Правка",
  "menu_edit_copyaddr": "Копировать адрес",
  "menu_edit_selectaddr": "Выделить адрес",
  "menu_edit_find": "Найти на странице",
  "menu_view": "Вид",
  "menu_view_reload": "Обновить",
  "menu_view_home": "Домашняя страница",
  "menu_view_zoomin": "Увеличить",
  "menu_view_zoomout": "Уменьшить",
  "menu_view_zoomreset": "Обычный масштаб",
  "menu_view_fullscreen": "Во весь экран",
  "menu_fav": "Избранное",
  "menu_fav_add": "Добавить в избранное",
  "menu_fav_show": "Показать избранное",
  "menu_fav_showhist": "Показать историю",
  "menu_tools": "Инструменты",
  "menu_tools_tm": "Машина времени (веб 1999 года)",
  "menu_tools_theme_eol": "Тема EOL",
  "menu_tools_theme_classic": "Тема Classic 98",
  "menu_tools_theme_aqua": "Тема Aqua 2000",
  "menu_tools_theme_night": "Тема «Неоновая ночь»",
  "menu_tools_engine": "Искать через %s",
  "menu_tools_devtools": "Инструменты разработчика",
  "menu_tools_clearhist": "Очистить историю",
  "menu_tools_lang": "Язык",
  "menu_help": "?",
  "menu_help_about": "О EOL Explorer",
  "about_body": "EOL Explorer 1.0<br><br>Браузер с видом 90-х и современным движком (Chromium).",
  "home_search_placeholder": "Что вы ищете сегодня?",
  "home_search_btn": "Найти",
  "home_cat_web": "Веб",
  "home_cat_images": "Картинки",
  "home_cat_video": "Видео",
  "home_cat_news": "Новости",
  "home_cat_maps": "Карты",
  "home_tab_explore": "Обзор",
  "home_tab_retro": "Ретро",
  "home_tab_fun": "Развлечения",
  "home_tab_tools": "Инструменты",
  "home_hero_title": "Назад в 1999-й",
  "home_hero_text": "С Машиной времени любой сайт открывается таким, каким он был в 1999 году, благодаря Internet Archive.",
  "home_tm_on": "⏪ Машина времени: ВКЛ (выключить)",
  "home_tm_off": "⏪ Включить Машину времени",
  "home_lcd_time": "Точное время",
  "home_lcd_visits": "Посетители",
  "home_favs_title": "Ваше избранное",
  "home_favs_empty": "Пока пусто.",
  "greet_morning": "Доброе утро",
  "greet_afternoon": "Добрый день",
  "greet_evening": "Добрый вечер",
  "home_marquee": "★ Добро пожаловать в EOL Explorer ★ Браузер, который выглядит как в 1999-м, а работает быстро, как сегодня ★ Рекомендуемое разрешение 800x600 (но и 4K подойдёт) ★ Сайт в разработке 🚧 ★"
 },
 "zh": {
  "url_placeholder": "输入网址或搜索内容…",
  "go": "前往",
  "search_placeholder": "搜索",
  "back": "后退",
  "forward": "前进",
  "stop": "停止",
  "reload": "刷新",
  "home": "主页",
  "favorites": "收藏夹",
  "history": "历史记录",
  "channels": "频道",
  "find_label": "查找：",
  "err_title": "无法打开该页面",
  "err_retry": "重试",
  "status_done": "完成",
  "status_local": "🏠 本地",
  "status_secure": "🔒 安全连接",
  "status_internet": "🌐 互联网",
  "status_opening": "正在打开 %s…",
  "status_fav_added": "已添加到收藏夹：%s",
  "status_fav_home": "无法将主页添加到收藏夹",
  "status_addr_copied": "地址已复制",
  "status_engine": "默认搜索引擎：%s",
  "status_hist_cleared": "历史记录已清除",
  "status_tm_on": "时光机已开启：网站会以 1999 年的样子打开",
  "status_tm_off": "时光机已关闭",
  "tab_home": "主页",
  "panel_fav_empty": "暂无收藏。打开一个网页后按 Ctrl+D。",
  "panel_hist_empty": "历史记录为空。",
  "menu_file": "文件",
  "menu_file_newtab": "新建标签页",
  "menu_file_closetab": "关闭标签页",
  "menu_edit": "编辑",
  "menu_edit_copyaddr": "复制网址",
  "menu_edit_selectaddr": "选择网址",
  "menu_edit_find": "在页面中查找",
  "menu_view": "查看",
  "menu_view_reload": "刷新",
  "menu_view_home": "主页",
  "menu_view_zoomin": "放大",
  "menu_view_zoomout": "缩小",
  "menu_view_zoomreset": "重置缩放",
  "menu_view_fullscreen": "全屏",
  "menu_fav": "收藏夹",
  "menu_fav_add": "添加到收藏夹",
  "menu_fav_show": "显示收藏夹",
  "menu_fav_showhist": "显示历史记录",
  "menu_tools": "工具",
  "menu_tools_tm": "时光机（1999 年的网络）",
  "menu_tools_theme_eol": "EOL 主题",
  "menu_tools_theme_classic": "经典 98 主题",
  "menu_tools_theme_aqua": "Aqua 2000 主题",
  "menu_tools_theme_night": "霓虹夜晚主题",
  "menu_tools_engine": "使用 %s 搜索",
  "menu_tools_devtools": "开发者工具",
  "menu_tools_clearhist": "清除历史记录",
  "menu_tools_lang": "语言",
  "menu_help": "?",
  "menu_help_about": "关于 EOL Explorer",
  "about_body": "EOL Explorer 1.0<br><br>拥有 90 年代外观、搭载现代内核（Chromium）的浏览器。",
  "home_search_placeholder": "今天想找什么？",
  "home_search_btn": "搜索",
  "home_cat_web": "网页",
  "home_cat_images": "图片",
  "home_cat_video": "视频",
  "home_cat_news": "新闻",
  "home_cat_maps": "地图",
  "home_tab_explore": "探索",
  "home_tab_retro": "复古",
  "home_tab_fun": "娱乐",
  "home_tab_tools": "工具",
  "home_hero_title": "回到 1999 年",
  "home_hero_text": "借助时光机和互联网档案馆，每个网站都会以 1999 年的样子打开。",
  "home_tm_on": "⏪ 时光机：已开启（关闭）",
  "home_tm_off": "⏪ 开启时光机",
  "home_lcd_time": "当前时间",
  "home_lcd_visits": "访客数",
  "home_favs_title": "你的收藏",
  "home_favs_empty": "暂无。",
  "greet_morning": "早上好",
  "greet_afternoon": "下午好",
  "greet_evening": "晚上好",
  "home_marquee": "★ 欢迎使用 EOL Explorer ★ 拥有 1999 年的界面，却有今天的速度 ★ 推荐分辨率 800x600（4K 也没问题）★ 网站建设中 🚧 ★"
 },
 "ja": {
  "url_placeholder": "アドレスまたは検索語を入力…",
  "go": "移動",
  "search_placeholder": "検索",
  "back": "戻る",
  "forward": "進む",
  "stop": "中止",
  "reload": "再読み込み",
  "home": "ホーム",
  "favorites": "お気に入り",
  "history": "履歴",
  "channels": "チャンネル",
  "find_label": "検索：",
  "err_title": "ページを開けませんでした",
  "err_retry": "再試行",
  "status_done": "完了",
  "status_local": "🏠 ローカル",
  "status_secure": "🔒 安全な接続",
  "status_internet": "🌐 インターネット",
  "status_opening": "%s を開いています…",
  "status_fav_added": "お気に入りに追加: %s",
  "status_fav_home": "ホームページはお気に入りに追加できません",
  "status_addr_copied": "アドレスをコピーしました",
  "status_engine": "既定の検索エンジン: %s",
  "status_hist_cleared": "履歴を消去しました",
  "status_tm_on": "タイムマシン ON: サイトは1999年の見た目で開きます",
  "status_tm_off": "タイムマシン OFF",
  "tab_home": "ホームページ",
  "panel_fav_empty": "お気に入りはまだありません。ページを開いて Ctrl+D を押してください。",
  "panel_hist_empty": "履歴はありません。",
  "menu_file": "ファイル",
  "menu_file_newtab": "新しいタブ",
  "menu_file_closetab": "タブを閉じる",
  "menu_edit": "編集",
  "menu_edit_copyaddr": "アドレスをコピー",
  "menu_edit_selectaddr": "アドレスを選択",
  "menu_edit_find": "ページ内検索",
  "menu_view": "表示",
  "menu_view_reload": "再読み込み",
  "menu_view_home": "ホームページ",
  "menu_view_zoomin": "拡大",
  "menu_view_zoomout": "縮小",
  "menu_view_zoomreset": "ズームをリセット",
  "menu_view_fullscreen": "全画面表示",
  "menu_fav": "お気に入り",
  "menu_fav_add": "お気に入りに追加",
  "menu_fav_show": "お気に入りを表示",
  "menu_fav_showhist": "履歴を表示",
  "menu_tools": "ツール",
  "menu_tools_tm": "タイムマシン（1999年のウェブ）",
  "menu_tools_theme_eol": "EOL テーマ",
  "menu_tools_theme_classic": "Classic 98 テーマ",
  "menu_tools_theme_aqua": "Aqua 2000 テーマ",
  "menu_tools_theme_night": "ネオンナイト テーマ",
  "menu_tools_engine": "%s で検索",
  "menu_tools_devtools": "デベロッパーツール",
  "menu_tools_clearhist": "履歴を消去",
  "menu_tools_lang": "言語",
  "menu_help": "?",
  "menu_help_about": "EOL Explorer について",
  "about_body": "EOL Explorer 1.0<br><br>90年代の見た目と最新のエンジン（Chromium）を持つブラウザ。",
  "home_search_placeholder": "今日は何をお探しですか？",
  "home_search_btn": "検索",
  "home_cat_web": "ウェブ",
  "home_cat_images": "画像",
  "home_cat_video": "動画",
  "home_cat_news": "ニュース",
  "home_cat_maps": "地図",
  "home_tab_explore": "探索",
  "home_tab_retro": "レトロ",
  "home_tab_fun": "エンタメ",
  "home_tab_tools": "ツール",
  "home_hero_title": "1999年へ戻る",
  "home_hero_text": "タイムマシンを使うと、Internet Archiveのおかげでどのサイトも1999年当時の姿で開きます。",
  "home_tm_on": "⏪ タイムマシン：ON（オフにする）",
  "home_tm_off": "⏪ タイムマシンをオンにする",
  "home_lcd_time": "現在時刻",
  "home_lcd_visits": "訪問者数",
  "home_favs_title": "お気に入り",
  "home_favs_empty": "まだありません。",
  "greet_morning": "おはようございます",
  "greet_afternoon": "こんにちは",
  "greet_evening": "こんばんは",
  "home_marquee": "★ EOL Explorer へようこそ ★ 1999年のように閲覧できて、今日のように高速 ★ 推奨解像度 800x600（4KでもOK）★ サイトは建設中です 🚧 ★"
 },
 "ar": {
  "url_placeholder": "اكتب عنوانًا أو ابحث…",
  "go": "اذهب",
  "search_placeholder": "بحث",
  "back": "رجوع",
  "forward": "للأمام",
  "stop": "إيقاف",
  "reload": "تحديث",
  "home": "الرئيسية",
  "favorites": "المفضلة",
  "history": "السجل",
  "channels": "القنوات",
  "find_label": "بحث:",
  "err_title": "تعذر فتح الصفحة",
  "err_retry": "إعادة المحاولة",
  "status_done": "تم",
  "status_local": "🏠 محلي",
  "status_secure": "🔒 اتصال آمن",
  "status_internet": "🌐 الإنترنت",
  "status_opening": "جارٍ فتح %s…",
  "status_fav_added": "أُضيف إلى المفضلة: %s",
  "status_fav_home": "لا يمكن إضافة الصفحة الرئيسية إلى المفضلة",
  "status_addr_copied": "تم نسخ العنوان",
  "status_engine": "محرك البحث الافتراضي: %s",
  "status_hist_cleared": "تم مسح السجل",
  "status_tm_on": "آلة الزمن مفعّلة: تُفتح المواقع كما كانت عام 1999",
  "status_tm_off": "آلة الزمن معطّلة",
  "tab_home": "الصفحة الرئيسية",
  "panel_fav_empty": "لا مفضلة بعد. افتح صفحة واضغط Ctrl+D.",
  "panel_hist_empty": "السجل فارغ.",
  "menu_file": "ملف",
  "menu_file_newtab": "علامة تبويب جديدة",
  "menu_file_closetab": "إغلاق علامة التبويب",
  "menu_edit": "تحرير",
  "menu_edit_copyaddr": "نسخ العنوان",
  "menu_edit_selectaddr": "تحديد العنوان",
  "menu_edit_find": "بحث في الصفحة",
  "menu_view": "عرض",
  "menu_view_reload": "تحديث",
  "menu_view_home": "الصفحة الرئيسية",
  "menu_view_zoomin": "تكبير",
  "menu_view_zoomout": "تصغير",
  "menu_view_zoomreset": "إعادة ضبط التكبير",
  "menu_view_fullscreen": "ملء الشاشة",
  "menu_fav": "المفضلة",
  "menu_fav_add": "إضافة إلى المفضلة",
  "menu_fav_show": "إظهار المفضلة",
  "menu_fav_showhist": "إظهار السجل",
  "menu_tools": "أدوات",
  "menu_tools_tm": "آلة الزمن (ويب 1999)",
  "menu_tools_theme_eol": "مظهر EOL",
  "menu_tools_theme_classic": "مظهر Classic 98",
  "menu_tools_theme_aqua": "مظهر Aqua 2000",
  "menu_tools_theme_night": "مظهر الليل النيون",
  "menu_tools_engine": "البحث باستخدام %s",
  "menu_tools_devtools": "أدوات المطوّر",
  "menu_tools_clearhist": "مسح السجل",
  "menu_tools_lang": "اللغة",
  "menu_help": "؟",
  "menu_help_about": "حول EOL Explorer",
  "about_body": "EOL Explorer 1.0<br><br>متصفح بمظهر التسعينيات ومحرك اليوم (Chromium).",
  "home_search_placeholder": "عمّ تبحث اليوم؟",
  "home_search_btn": "بحث",
  "home_cat_web": "الويب",
  "home_cat_images": "صور",
  "home_cat_video": "فيديو",
  "home_cat_news": "أخبار",
  "home_cat_maps": "خرائط",
  "home_tab_explore": "استكشاف",
  "home_tab_retro": "قديم",
  "home_tab_fun": "ترفيه",
  "home_tab_tools": "أدوات",
  "home_hero_title": "عد إلى 1999",
  "home_hero_text": "باستخدام آلة الزمن، يُفتح كل موقع كما كان في عام 1999 بفضل أرشيف الإنترنت.",
  "home_tm_on": "⏪ آلة الزمن: مفعّلة (إيقاف)",
  "home_tm_off": "⏪ تفعيل آلة الزمن",
  "home_lcd_time": "الوقت الحالي",
  "home_lcd_visits": "الزوار",
  "home_favs_title": "مفضلتك",
  "home_favs_empty": "لا شيء بعد.",
  "greet_morning": "صباح الخير",
  "greet_afternoon": "مساء الخير",
  "greet_evening": "مساء الخير",
  "home_marquee": "★ مرحبًا بك في EOL Explorer ★ متصفح يتصفح كما في 1999 لكنه سريع كاليوم ★ الدقة الموصى بها 800×600 (لكن 4K يعمل أيضًا) ★ الموقع قيد الإنشاء 🚧 ★"
 }
};
